inherit_mode:
  merge:
    - Exclude
    - Include
require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - included
    - class_methods

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 50
  IgnoredMethods:
    - included
    - class_methods
    - run_callbacks

Metrics/ClassLength:
  Max: 200
  Exclude:
    - "lib/tag_options/property_handler/tailwind_css.rb"
    - "test/**/*_test.rb"

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "lib/tag_options/property_handler/tailwind_css.rb"

Metrics/ModuleLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 14

Naming/MethodName:
  Exclude:
    - "lib/tag_options.rb"

Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/RegexpLiteral:
  AllowInnerSlashes: true
